// 56개 형용사(조하리의 창 원본 세트). 기존 프로토타입(johari_prototype.html)에서 그대로 이식.
export type Adjective = { id: string; en: string; ko: string };

export const ADJECTIVES: Adjective[] = [
  { id: "able", en: "able", ko: "재능있는" },
  { id: "accepting", en: "accepting", ko: "수용적인" },
  { id: "adaptable", en: "adaptable", ko: "적응력이 있는" },
  { id: "bold", en: "bold", ko: "대담한" },
  { id: "calm", en: "calm", ko: "침착한/차분한" },
  { id: "caring", en: "caring", ko: "배려하는" },
  { id: "cheerful", en: "cheerful", ko: "쾌활한" },
  { id: "clever", en: "clever", ko: "영리한" },
  { id: "extrovert", en: "extrovert", ko: "외향적인" },
  { id: "friendly", en: "friendly", ko: "친절한/상냥한" },
  { id: "giving", en: "giving", ko: "마음이 넓은" },
  { id: "happy", en: "happy", ko: "행복한" },
  { id: "helpful", en: "helpful", ko: "도움이 되는" },
  { id: "idealistic", en: "idealistic", ko: "이상주의적인" },
  { id: "independent", en: "independent", ko: "독립적인" },
  { id: "ingenious", en: "ingenious", ko: "독창적인" },
  { id: "modest", en: "modest", ko: "겸손한" },
  { id: "nervous", en: "nervous", ko: "신경이 과민한" },
  { id: "observant", en: "observant", ko: "관찰력 있는" },
  { id: "optimistic", en: "optimistic", ko: "낙천적인" },
  { id: "organized", en: "organized", ko: "계획적인" },
  { id: "patient", en: "patient", ko: "인내심 있는" },
  { id: "powerful", en: "powerful", ko: "영향력 있는" },
  { id: "proud", en: "proud", ko: "자랑스러운" },
  { id: "self-conscious", en: "self-conscious", ko: "자의식이 강한" },
  { id: "sensible", en: "sensible", ko: "합리적/실용적인" },
  { id: "sentimental", en: "sentimental", ko: "감성적인" },
  { id: "shy", en: "shy", ko: "수줍어 하는" },
  { id: "silly", en: "silly", ko: "어리석은" },
  { id: "smart", en: "smart", ko: "말쑥한" },
  { id: "spontaneous", en: "spontaneous", ko: "즉흥적인" },
  { id: "sympathetic", en: "sympathetic", ko: "동정심 있는" },
  { id: "dependable", en: "dependable", ko: "신뢰할 수 있는(dependable)" },
  { id: "dignified", en: "dignified", ko: "위엄/품위있는" },
  { id: "energetic", en: "energetic", ko: "활동적인" },
  { id: "confident", en: "confident", ko: "자신감 있는" },
  { id: "complex", en: "complex", ko: "복잡한" },
  { id: "wise", en: "wise", ko: "지혜로운/현명한" },
  { id: "responsive", en: "responsive", ko: "호응적인" },
  { id: "searching", en: "searching", ko: "면밀한/탐색적인" },
  { id: "logical", en: "logical", ko: "논리적인" },
  { id: "loving", en: "loving", ko: "다정한" },
  { id: "mature", en: "mature", ko: "성숙한" },
  { id: "knowledgeable", en: "knowledgeable", ko: "박식한" },
  { id: "kind", en: "kind", ko: "친절한" },
  { id: "warm", en: "warm", ko: "따뜻한" },
  { id: "relaxed", en: "relaxed", ko: "느긋한" },
  { id: "religious", en: "religious", ko: "독실한" },
  { id: "reflective", en: "reflective", ko: "사색적인" },
  { id: "introvert", en: "introvert", ko: "내향적인" },
  { id: "congenial", en: "congenial", ko: "마음이 맞는" },
  { id: "trustworthy", en: "trustworthy", ko: "신뢰할 수 있는(trustworthy)" },
  { id: "self-assertive", en: "self-assertive", ko: "자기주장이 강한" },
  { id: "tense", en: "tense", ko: "날카로운" },
  { id: "aggressive", en: "aggressive", ko: "공격적인" },
  { id: "intelligent", en: "intelligent", ko: "똑똑한/지적인" },
];

export const ADJ_BY_ID = Object.fromEntries(ADJECTIVES.map((a) => [a.id, a]));
export const ADJECTIVE_IDS = new Set(ADJECTIVES.map((a) => a.id));

export const PICK_MIN = 5;
export const PICK_REC = 6; // 권장 상한(강제 아님)
